### PR TITLE
added try except to combinatorial promoter

### PR DESCRIPTION
**Pull request by dr3y**

### CODE REVIEW

**Comment by zoltuz** [comment]
@dr3y 
two errors left, check the Travis log:
https://travis-ci.org/github/zoltuz/biocrnpyler/jobs/698665530
Screenshot 2020-06-15 at 21 07 18
Screenshot 2020-06-15 at 21 07 45
You need to catch the error and do something with it. In other examples, there a simple pass in the catch case.

**Comment by dr3y** [comment]
ah yes sorry about this. I couldn't test it on my machine because I didn't want to uninstall bioscrape.

**Comment by zoltuz** [comment]
No worries, once it works Travis should be able to run all tests, which you can see below in the checks area.

**Comment by zoltuz** [comment]
Great! it works now. Thanks for the help, Andrey! @dr3y

**Pull request merged**
